### ISSUE TITLE
Import error due release 3.5 of Python

### ISSUE THREAD

**Issue by blazaid** [necaris/python3-openid#14]
With the release of Python 3.5, the HTMLParserError exception has been removed (it was deprecated since version 3.3), so now importing it results in an Import exception.

The file yadis/parsehtml.py in line 3 imports HTMLParserError.

**Comment by necaris** [comment]
Thanks for the report!

**Comment by blazaid** [comment]
According to the documentation (https://docs.python.org/3.3/library/html.parser.html?highlight=htmlparseerror), the exception is never thrown so it looks like the solution is as easy as deleting the exception block and the import.

**Comment by necaris** [comment]
Thank you for the pull request! I've uploaded a new version to PyPI with
the fix: https://pypi.python.org/pypi/python3-openid

On Tue, Sep 15, 2015 at 2:36 PM, blazaid <notifications@github.com> wrote:

> According to the documentation (
> https://docs.python.org/3.3/library/html.parser.html?highlight=htmlparseerror),
> the exception is never thrown so it looks like the solution is as easy as
> deleting the exception block and the import.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/necaris/python3-openid/issues/14#issuecomment-140493276>
> .
>



-- 
Rami Chowdhury
"A mind all logic is like a knife all blade - it makes the hand bleed that
uses it." -- Rabindranath Tagore
+1-408-372-6496 / +44-7581-430-517 / +88-0189-245544
