### ISSUE TITLE
Outdated releases

### ISSUE THREAD

**Issue by BOHverkill** [necaris/python3-openid#22]
Hi!
Can you please update the releases to the newest version so I am able to work with a python 3.5 compatible version.
Thank you!

**Comment by necaris** [comment]
Sure thing -- I've updated the tags and releases on Github so they should be pointing to the latest version.

Please note, though, that the best way of installing this package is by using [pip](http://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/) which should always have an up-to-date version.

**Comment by BOHverkill** [comment]
Thank you!
