### ISSUE TITLE
Tests failing using python 3.5

### ISSUE THREAD

**Issue by simonsmiley** [necaris/python3-openid#23]
Is this expected?

**Comment by necaris** [comment]
@simonsmiley Which version are you using? The most recent version ([3.0.9](https://pypi.python.org/pypi/python3-openid/3.0.9)) should support 3.5, although the Travis tests are currently failing because the Django examples haven't been updated.

**Comment by simonsmiley** [comment]
I am using 3.0.9.

I am the packager for archlinux (aur). I just added some functionality to run the tests before building the package, and it failed. I guess I will ignore the tests for now. :-)

**Comment by necaris** [comment]
@simonsmiley Sorry about that -- I'll get the Django examples updated or skipped shortly and you should be able to re-enable the tests.

As an Arch user myself, many thanks for your work with the AUR!

**Comment by simonsmiley** [comment]
NP, I updated the package without the tests. I will enable them for the next release then :-)
