### ISSUE TITLE
Django makemessages -a gives encoding error.

### ISSUE THREAD

**Issue by gabn88** [necaris/python3-openid#24]
xgettext: ./lib/python3.4/site-packages/openid/__init__.py:1: Unknown encoding "utf-8-". Proceeding    with ASCII instead.
    xgettext: ./lib/python3.4/site-packages/openid/association.py:2: Unknown encoding "utf-8-". Proceeding  with ASCII instead.
    xgettext: ./lib/python3.4/site-packages/openid/yadis/__init__.py:1: Unknown encoding "utf-8-". Proceeding with ASCII instead.

**Comment by gabn88** [comment]
I think the spaces around 'utf-8' are missing the above files, should be easy to fix :)

**Comment by necaris** [comment]
@gabn88 Thank you for the PR -- this should be fixed by #26
