### ISSUE TITLE
Wheel support

### ISSUE THREAD

**Issue by kevin-brown** [necaris/python3-openid#30]
http://pythonwheels.com/

Right now, only the `tar.gz` file is being distributed on PyPI for [python3-openid](https://pypi.python.org/pypi/python3-openid), which isn't _that much_ of an issue, but it does add some time to installing the package.

This package should be compatible with the Wheel format, considering it doesn't appear to have any C dependencies and it is compatible with both Python 2 and 3. As a result, you should only need to generate a universal wheel and then everyone (on all systems) will get the ability to install python3-openid with just the wheel, without having to do any extra work.

**Comment by necaris** [comment]
Thanks @kevin-brown, that's a good thought. I'll look into wheels and possibly backporting Python 2 support.

**Comment by kevin-brown** [comment]
> possibly backporting Python 2 support

...that was my fault for using the same template, my bad.

**Comment by necaris** [comment]
Well, backporting might be a good idea so people don't need to maintain a dependency on the old package for Python 2.

**Comment by ghickman** [comment]
@necaris – you should be able to wheel this project already with the command mentioned in #31, as long as you don't set the `universal` flag in setup.cfg.  Would a Makefile with a release command help?

**Comment by necaris** [comment]
@kevin-brown @ghickman FYI: [new release](https://pypi.python.org/pypi/python3-openid/3.1.0) published, including a wheel :smile:
