### ISSUE TITLE
TypeError: unorderable types: Association() < Association()

### ISSUE THREAD

**Issue by tono-gw** [necaris/python3-openid#33]
I have this error with python3 using django framework:

`TypeError: unorderable types: Association() < Association()`

This error occurred when 2 or more record in the openid_associations table have the same value for the "issued" column."

And I debugged at line 245 in python3-openid/openid/store/sqlstore.py
```
245             print(associations)
246             if associations:
247                 associations.sort()
248                 return associations[-1][1]
249             else:
250                 return None
```
It's result is..
`[(1480070610, <openid.association.Association HMAC-SHA1 b30a6665e79dd5af>), (1480070610, <openid.association.Association HMAC-SHA1 cacca1f99cd2dc4d>)]`

Data type "Association" is compared when "issued" are same value, but it can't be comparative.

**Comment by necaris** [comment]
@tono-gw I'm sorry I haven't gotten to this till now. I can confirm that error would indeed occur when trying to sort `Association`s, and I just pushed e55249c which should fix it. Thank you for the report, and I'll ping you when I create a new release including the fix!

**Comment by necaris** [comment]
@tono-gw FYI: [new release](https://pypi.python.org/pypi/python3-openid/3.1.0) published which includes a fix for this issue.
