### ISSUE TITLE
Logging is using the root logger

### ISSUE THREAD

**Issue by therefromhere** [necaris/python3-openid#43]
I noticed that all the log calls are direct to the root logger, which isn't ideal.

FWIW this was fixed in python-openid2 in https://github.com/ziima/python-openid/commit/95a143cc06edae839178c9d99d6c89dc43b99d40

**Comment by necaris** [comment]
Thanks @therefromhere for bringing this up! Should be resolved by #50. This will hopefully also help with https://github.com/pennersr/django-allauth/issues/1314 :-)
