### ISSUE TITLE
Please release the latest change into pypi.org

### ISSUE THREAD

**Issue by earthday** [necaris/python3-openid#54]
@necaris Thanks for resolve PostgreSQL package issue, is there any plan or schedule to release this change to https://pypi.org/project/python3-openid/ as a new version?

_Originally posted by @earthday in https://github.com/necaris/python3-openid/pull/49#issuecomment-647885074_

**Comment by necaris** [comment]
@earthday apologies for the delayed response. Just released version 3.2.0: https://pypi.org/project/python3-openid/3.2.0/

**Comment by earthday** [comment]
@necaris Thanks. 👍
