### ISSUE TITLE
Cleanup Nonces

### ISSUE THREAD

**Issue by DavidHwu** [necaris/python3-openid#9]
Kindly ask that we clarify how nonces are cleaned up and managed.

I have this operational, but using the FileOpenIDStore class, I am seeing Nonce being created on each login x user.  Each Logout and Login gets Nonces created each same user.  

While this makes sense, it would be good to understand how Nonce are GC'd.  And if the clients of this lib can have any control over.
In the case of the FileOpenIDStore how this can be cleaned up as these are collecting and piling up.  In the database for storing Nonce (ie. SQLStore) same would be reflected in number of records.

**Comment by necaris** [comment]
@DavidHwu -- I'm afraid the library has no built-in mechanism for garbage-collecting the old nonces, either using the filesystem store or the SQL store. I do not currently have a plan to add this feature, however I would be very happy to help you implement it if you would like to submit a pull request!
